#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/wait.h>

// Write a C program (we'll refer to it as A) that creates a child process B. Process B generates one random number N between 100 and 1000. Process A keeps generating and sending random numbers between 50 and 1050 to B until the absolute difference between the number generated by A and the number generated by B is less than 50. B prints the generated numbers and all the received numbers. A will print at the end the number of numbers generated until the stop condition was met.

int main() {
	int A2B[2], B2A[2], f, running = 1, nrA;
		
	if(pipe(A2B) == -1) {
		perror("1st pipe error");
		exit(1);
	}

	if(pipe(B2A) == -1) {
		perror("2nd pipe error");
		exit(1);
	}

	srand(time(0));

	f = fork();
	if(f == -1) {
		perror("1st fork error");
		exit(1);
	} else if(f == 0) {

		close(A2B[1]);
		close(B2A[0]);
		
		int n = random() % 901 + 100;
		printf("B generated %d\n", n);

		while(1) {
			
			if(read(A2B[0], &nrA, sizeof(int)) < 0) {
				perror("B - read error");
				exit(1);
			}
			
			printf("B read %d from A, running = %d\n", nrA, running);

			int diff = abs(n - nrA);

			printf("diff = %d\n", diff);
			
			if(diff < 50) {
				running = 0;
			}

			if(write(B2A[1], &running, sizeof(int)) < 0) {
				perror("B - write error");
				exit(1);
			}

			if(running == 0) {
				break;
			}
		}

		exit(0);

	} else {

		close(B2A[1]);
		close(A2B[0]);

		while(running) {
			
			nrA = random() % 1001 + 50;

			if(write(A2B[1], &nrA, sizeof(int)) < 0) {
				perror("A - write error");
				exit(1);
			}

			printf("A generated %d, running = %d\n", nrA, running);
			
			if(read(B2A[0], &running, sizeof(int)) < 0) {
				perror("A - read error");
				exit(1);
			}

			if(running == 0) {
				printf("stopped");
				break;
			}
		}
		
		close(A2B[1]);
		close(B2A[0]);
		wait(0);
	}

	return 0;
}
