USE CityPlanning

SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ

BEGIN TRAN
    SELECT * FROM dbo.Project

    WAITFOR DELAY '00:00:05'

    SELECT * FROM dbo.Project

COMMIT TRAN
