USE [master]
GO
/****** Object:  Database [CityPlanning]    Script Date: 15.05.2025 12:56:28 ******/
CREATE DATABASE [CityPlanning]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CityPlanning', FILENAME = N'C:\Users\cretuluca\CityPlanning.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CityPlanning_log', FILENAME = N'C:\Users\cretuluca\CityPlanning_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [CityPlanning] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CityPlanning].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CityPlanning] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CityPlanning] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CityPlanning] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CityPlanning] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CityPlanning] SET ARITHABORT OFF 
GO
ALTER DATABASE [CityPlanning] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [CityPlanning] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CityPlanning] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CityPlanning] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CityPlanning] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CityPlanning] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CityPlanning] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CityPlanning] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CityPlanning] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CityPlanning] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CityPlanning] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CityPlanning] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CityPlanning] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CityPlanning] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CityPlanning] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CityPlanning] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CityPlanning] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CityPlanning] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CityPlanning] SET  MULTI_USER 
GO
ALTER DATABASE [CityPlanning] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CityPlanning] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CityPlanning] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CityPlanning] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CityPlanning] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CityPlanning] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [CityPlanning] SET QUERY_STORE = ON
GO
ALTER DATABASE [CityPlanning] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [CityPlanning]
GO
/****** Object:  Table [dbo].[Budget]    Script Date: 15.05.2025 12:56:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Budget](
	[BudgetID] [int] IDENTITY(1,1) NOT NULL,
	[TotalValue] [int] NULL,
	[SpentSoFar] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[BudgetID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[City]    Script Date: 15.05.2025 12:56:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[City](
	[CityID] [int] IDENTITY(1,1) NOT NULL,
	[CityName] [varchar](20) NULL,
	[BudgetID] [int] NOT NULL,
	[Population] [int] NULL,
	[Surface] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[CityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Department]    Script Date: 15.05.2025 12:56:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Department](
	[DepartmentID] [int] IDENTITY(1,1) NOT NULL,
	[DepartmentName] [varchar](20) NULL,
	[EmployeesNumber] [int] NULL,
	[CityID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DepartmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Employee]    Script Date: 15.05.2025 12:56:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employee](
	[EmployeeID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](20) NULL,
	[DepartmentID] [int] NOT NULL,
	[PositionID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EmployeeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Position]    Script Date: 15.05.2025 12:56:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Position](
	[PositionID] [int] IDENTITY(1,1) NOT NULL,
	[PositionName] [varchar](20) NULL,
	[Salary] [int] NULL,
	[EducationLevel] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[PositionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Project]    Script Date: 15.05.2025 12:56:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Project](
	[ProjectID] [int] IDENTITY(1,1) NOT NULL,
	[ProjectName] [varchar](20) NULL,
	[StartDate] [date] NULL,
	[EndDate] [date] NULL,
	[SupplierID] [int] NOT NULL,
	[SponsorshipID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ProjectID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Sponsorship]    Script Date: 15.05.2025 12:56:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Sponsorship](
	[SponsorshipID] [int] IDENTITY(1,1) NOT NULL,
	[SponsorName] [varchar](20) NULL,
	[Value] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[SponsorshipID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Supplier]    Script Date: 15.05.2025 12:56:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Supplier](
	[SupplierID] [int] IDENTITY(1,1) NOT NULL,
	[SupplierName] [varchar](20) NULL,
	[Revenue] [int] NULL,
	[FoundingDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[SupplierID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transactions]    Script Date: 15.05.2025 12:56:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transactions](
	[TransactionID] [int] IDENTITY(1,1) NOT NULL,
	[Price] [int] NULL,
	[Date] [date] NULL,
	[DepartmentID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TransactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[City]  WITH CHECK ADD FOREIGN KEY([BudgetID])
REFERENCES [dbo].[Budget] ([BudgetID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Department]  WITH CHECK ADD FOREIGN KEY([CityID])
REFERENCES [dbo].[City] ([CityID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD FOREIGN KEY([DepartmentID])
REFERENCES [dbo].[Department] ([DepartmentID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Employee]  WITH CHECK ADD FOREIGN KEY([PositionID])
REFERENCES [dbo].[Position] ([PositionID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Project]  WITH CHECK ADD FOREIGN KEY([SponsorshipID])
REFERENCES [dbo].[Sponsorship] ([SponsorshipID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Project]  WITH CHECK ADD FOREIGN KEY([SupplierID])
REFERENCES [dbo].[Supplier] ([SupplierID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Transactions]  WITH CHECK ADD FOREIGN KEY([DepartmentID])
REFERENCES [dbo].[Department] ([DepartmentID])
ON DELETE CASCADE
GO
USE [master]
GO
ALTER DATABASE [CityPlanning] SET  READ_WRITE 
GO

