USE CityPlanning

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

BEGIN TRAN
    SELECT * FROM Project

    WAITFOR DELAY '00:00:10'

    SELECT * FROM Project
COMMIT TRAN
